service: biller-backend
app: biller-backend
org: priscilla
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ${opt:region, "eu-west-2"},
  profile: ${opt:profile, "priscilla"}
  stage: ${opt:stage, "dev"}

functions:
  hello:
    handler: handler.hello

plugins:
  - '@serverless/enterprise-plugin'
